# Generated by Django 5.0.6 on 2024-07-21 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0002_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 19, 41, 7, 869511)),
        ),
        migrations.AlterField(
            model_name='user',
            name='owned_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', related_query_name='owner', to='monde.clothingitem'),
        ),
    ]
