# Generated by Django 5.0.6 on 2024-07-22 10:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0005_userprofile_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='monde.clothingitem'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 12, 22, 14, 147382)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cart_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monde.clothingitem'),
        ),
    ]
