# Generated by Django 5.0.6 on 2024-07-22 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0024_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 16, 2, 9, 976190)),
        ),
    ]
