# Generated by Django 5.0.6 on 2024-07-25 17:40

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0027_alter_cartitems_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='sections',
            field=models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('accessories', 'accessories'), ('girls', 'girls'), ('boys', 'boys'), ('summer', 'summer'), ('winter', 'winter'), ('casual', 'casual'), ('formal', 'formal')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 19, 38, 25, 303138)),
        ),
    ]
