# Generated by Django 5.0.6 on 2024-07-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0030_sections_remove_clothingitem_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 19, 53, 13, 698861)),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
