# Generated by Django 5.0.6 on 2024-07-27 18:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0033_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monde.clothingitem'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 26, 20, 17, 15, 590925)),
        ),
    ]
