# Generated by Django 5.0.6 on 2024-08-01 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0034_alter_cartitems_item_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=574.21),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 31, 13, 26, 28, 514792)),
        ),
    ]
