# Generated by Django 5.0.6 on 2024-08-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0036_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userowneditems',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 31, 14, 1, 56, 776960)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=474.98),
        ),
    ]
