# Generated by Django 5.0.6 on 2024-08-28 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0040_alter_review_options_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userowneditems',
            name='amount_purchased',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 9, 27, 15, 16, 59, 252849)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=95.69),
        ),
    ]
