# Generated by Django 5.0.6 on 2024-08-28 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0041_userowneditems_amount_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 9, 27, 15, 17, 21, 764836)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=962.2),
        ),
    ]
