# Generated by Django 5.0.6 on 2024-09-12 02:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0042_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(default='OIP.jpg', upload_to='media/images/%y'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 4, 38, 32, 408085)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=33.2),
        ),
    ]
