# Generated by Django 5.0.6 on 2024-09-12 03:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0043_alter_clothingitem_image_alter_clothingitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 5, 17, 49, 180896)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=281.7),
        ),
    ]
