# Generated by Django 5.0.6 on 2025-05-06 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0044_alter_cartitems_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 5, 9, 33, 16, 752453)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.FloatField(default=0),
        ),
    ]
