# Generated by Django 5.0.6 on 2025-05-14 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0045_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(default='OIP.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 13, 14, 57, 54, 344842)),
        ),
    ]
