# Generated by Django 5.0.6 on 2025-05-16 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0046_alter_clothingitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 3, 17, 38, 781925)),
        ),
    ]
