# Generated by Django 5.0.6 on 2025-05-16 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0047_clothingitem_image_url_alter_clothingitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 3, 35, 26, 448054)),
        ),
    ]
