# Generated by Django 5.0.6 on 2025-05-16 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0048_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 4, 56, 9, 534887)),
        ),
    ]
