# Generated by Django 5.0.6 on 2025-05-20 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0051_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 19, 5, 43, 24, 278109)),
        ),
    ]
