# Generated by Django 5.0.6 on 2025-05-21 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0052_remove_clothingitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 13, 55, 33, 87054)),
        ),
    ]
