# Generated by Django 5.0.6 on 2025-05-23 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0054_alter_cartitems_item_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='rating',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 8, 48, 3, 637416)),
        ),
    ]
