# Generated by Django 5.0.6 on 2025-05-27 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0056_alter_clothingitem_shippingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 15, 43, 58, 531082)),
        ),
    ]
