# Generated by Django 5.0.6 on 2025-05-30 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monde', '0057_alter_clothingitem_shippingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='shippingDate',
            field=models.DateField(default=datetime.datetime(2025, 6, 29, 10, 12, 42, 146241)),
        ),
    ]
